services:
  portfolio:
    build:
      context: ../
      dockerfile: dockerfile
    container_name: portafolio-dev
    restart: always
    environment:
      - HOST=0.0.0.0
    ports:
      - "3000:3000"